#!/usr/bin/python

import shlex, subprocess, sys, os.path

dir = os.path.abspath(os.path.dirname(__file__))

# See if we've been given the sleep argument, store the rest.
args = sys.argv[1:]
sleep = False
if args.count('--sleep'):
    sleep = True
    args.remove('--sleep')
command_args = ' '.join(args)

# General options
args  = '%s/get_iplayer --nopurge --nocopyright --quiet' % dir
# Program locations
args += ' --mplayer=Binaries/mplayer --flvstreamer=Binaries/flvstreamer_macosx --lame=Binaries/lame --atomicparsley=Binaries/AtomicParsley --ffmpeg=Binaries/ffmpeg_leopard'.replace('Binaries', os.path.join(dir, 'Binaries'))
# Fetching options
args += ' --attempts=5 --versions=default --modes=flashvhigh,flashhigh,flashstd,flashnormal,flashaachigh,flashaacstd,flashaudio,wma'
# Output file options
args += ' --output=~/Movies --whitespace --subdir --subdir-format="<nameshort>" --file-prefix="<name> - <episode>" --command \'%s/add_to_itunes "<filename>"\'' % dir

# TV and Radio by default (unless PVRing, in which case use whatever we have there)
if 'pvr' not in command_args:
    args += ' --type tv,radio'

subprocess.call( shlex.split(args + ' ' + command_args) )

# If we were asked to, sleep the computer
if sleep: subprocess.call(['pmset', 'sleepnow'])
